services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  gameEmbeddings:
    image: pgvector/pgvector:pg18-trixie
    volumes:
      - game_embeddings_data:/var/lib/postgresql
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - "5433:5432"

  web:
    build: .
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - db
      - gameEmbeddings
    volumes:
      - .:/app:cached
    environment:
      EMBEDDING_DIM: 64
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - "5000:5000"
    command: >
      bash -c "python -m src.ingest.initialize_database && python -m src.ingest.initialize_game_embeddings && python -m src.ingest.generate_training_pairs && python -m src.models.train_two_tower_model && python -m src.ingest.store_game_embeddings && python -m src.ingest.train_lightgbm_lambdamart && python -m src.tools.metrics_tool && python -m src.webapp.app"

volumes:
  db_data:
  game_embeddings_data:


secrets:
  postgres_user:
    file: .secrets/postgres_user
  postgres_password:
    file: .secrets/postgres_password
  postgres_db:
    file: .secrets/postgres_db
